### ISSUE TITLE
dashicons do not always load - especially on mobile

### ISSUE THREAD

**Issue by postmastersteve** [netrivet/support#16]
![2016-04-07_10-02-45](https://cloud.githubusercontent.com/assets/275742/14355472/073e85ba-fcaf-11e5-8d1f-6470a2f43d6b.png)

**Comment by jaredh159** [comment]
@postmastersteve this is still an issue -- it's a matter of whether the user is logged in or not, not a mobile thing.  Because the `dashicons` font is enqueued for the WordPress admin bar, which is not present for non logged in users.

![2016-04-21_10-21-47](https://cloud.githubusercontent.com/assets/7050938/14712430/1a4d34ba-07ab-11e6-8266-4f42888afcc7.png)

**Comment by jaredh159** [comment]
You may be already aware of this, just thought I'd mention it because you fixed most of them by switching them to font awesome.

**Comment by postmastersteve** [comment]
Yes, fixed in https://github.com/netrivet/support/pull/19
